language: r
sudo: false

cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_site"

env:
  global:
  - secure: WalkdPBoN2dH9a+aMqqbxRd1jHxVc77fcpF4PWfgMAU8P4ic4x36i+KZe8r12gQn5lzf8M6kBnwN1tY9dad6ZpGH3ofHMNA+hx9f59n1s5B/oZTaVjc2RdUz7gQxtAsOzZtdANWd/jtOCe8EbPYlONILMbvpFvgTUpVrLgvO0BtwR/EVghQT42StlNK6tj3HC+eAu32YFZ1M7bJ1yqBbovhCg7httKo+yhVnpAfzpRHutP4NMQbhm82ME6jX6N+oNinXOSryD8luopU/dEkhrIoZPDVP+RAUe4qZ2Nh+vrEJISJTFtb+wFmZQoL1RRwX4cj+svmQdrZHBaYo0MidJVTk49kdTv/V/SO6IyVe9gVrzFKSrJp77ISGNcz7YUcscn8L33crFx7TmSaauW3VxOdjWy7IGjJuSZLcBHaahBgkaKz3M+W/LAU24ezN2JZc8YLcpNJomtHOHAksASn/UohA8BTvf0VBz/L0t7b2E0LRtzkQoO3y3C4aeX3MIRTeXWCDYMLBzOJPBJaOYNRe1/M0pNf2V8M92nOE49xqkdx/pDY2SdCKCr5ojAt1clU3bhoUO7F6k5pVOsKdUae21n11aWTTn2Igs+GhJyeIbb/9wawwFYLdinkZi+V9N3csuzaMF0QuxQysl/a4yI3skp2SszbGf203Oc80j6HJoxI=
  - secure: cFXDf0maWjcFAv/ZyAshHwmylKvkgptUg34Qz3nvAfIKAf0vPLdHD5nT9troHp24gQXrQ+qsisrJx2rWtEQwCZrGcCb/Jc6h760dcZMW7RkH5ISFJpAqScrrZ96vvIcVGyxM07f0eaEmvtB7aRroSWlZ3AXijPvbKt0AcJjFjY6Gyic+jYDiHmMGoDlNDQNOOXBWlb4JeEsZG6XRJ+52djlBOR5/nstYjOdfwUI3j/3gS3YJsIQ/eya3QUa9cM7KwXDOFBmPfqpEJ2hwtsO1Us/ua4BhaskaH18wjPWNDNEWLeuokhCYeMq6xCFq/SgAU7ouCc9r5yYOsGM9EsC60Pg2xNfTVLvQN4mbpa/BeJXqojAn3x7Xb0YGGu1qf1tf2rgBMUQbdwmo35Cs/0xKHmBTtwMo8YAc8wkU+1GfsLmCDtL1hjnQ8KJzXSFyw56JXaYJx8o3mNywl7pWTXDbVpuanPPgx++AVE0vkiT3/3iiKPt4ltaFym6yS57/g8+/rVf32sZpyLwSPG3nDOK2CeGrhs64fzYmvYhpgZuGgKdl17jtVejcAzK/4OaZz0g2QXNCOesQZuCuuXYiRv1rUg6yIrgucG/FgpGGs40Z5qK8vKLpRfUztJZ1haGCrsxvmhQQgvU2sENxsOaLoxXjsH7noXY8co0oZbp0r46Yqy4=

script:
- make -f build.mk

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  local_dir: _site
  github_token: "$GITHUB_TOKEN"

notifications:
  email: false
  slack:
    rooms:
    - secure: DSWbaupEfku/IbTIICJwcfkAkhUpdkTn+4QDcz7LZTOykd9McphAw5ezikIRmtnFdAafLxb0LvnjQ0VwumfU58S2Tbd9GTBT504RGVDqRGdfCDrVt4Q833JsZ+X7ZaPIS0AfBqGsLltpTzijQ6pjC6eku1w5kqAURQOrWCzujZ/qvmVH/Y1HUE364caNE3qHeDd05VIbmsgMrKwYHkUBxmfhLrCVe4/Zuo7BuzaTd6ELeCDTaBrlO7ibeDm/PtLmUaViUYf3g2tHPJKZ4gwG46ZEOTjI+k6FTCzR7UGF4qpkZtBK02AJgF7I5aenYqcL0uib51zyLI9LSJWS2UUKvH8yFEgr+/OVd8a8Fxf+nnG17uUBDZixlSKXq1nXE5FswkDFYwYT3A7dVkFtJQXBQ0dX9a46L2+vyl8IkudR2YAIV5Pabb+/8gvEWG4cw+HHEfK6m/PijGufsnRZ7eJnHSDLl/UIxHHEqtUjeTT44WXVMad5C4sIpeK/JqdOk+Jn/q+6OYhZnamGHE2QxLl2QwEAP9OBuJuYK4lLBBNSbg1TgJU75i5UF9p9oMmW3ZT1Qj+KFyrqufnXC9GYtZ8FsT33HM6lWaS9L4U0MvvNSvEEjLM3hjlrP+nea+2Kyu7FX+LZPfRAFi6ekStKtNJZqM6b0IF4y4tOhJoaxhJkVDA=
    - secure: bzz8qDOcCB8po7oOS3kS+S+Ycv1SSDixD0AQjT8/oMcybUTbLVyLElsA+t7iZVxN7jQevd4GHECIAkFF5FuqDxjwujVBW2bbRsaTdYFBlxJfepDWa1wJFgVhue/Kl1WRNG9YvpJuf2UEhmj0sHvlUidhr3knhZJOmbSXmLnZY0lHXVtEALuWHjrnqc+/OOTR1FFVrDv7l04EFLDfmRFsrRwDSZCs+tqm1OIvdhm+vvxn5T8mGShGEZg3LxMWe9FqAL7He5P2ktGDDhCBHMrgSdxk9ayMzlUXLWTZVq3ybdfSGsMukX5p+EtLEBZUznFgpRLvQif5Vlkj85s2tjMs40JumaZMtAtpk1U52EtMTYt+OS5shpSeb+n1fyA68O/KLyK57VnAlOmevi+RFCBTgHpz2AO7XGfobLWrc/K24f27Yd2bCkG/ag1yaK4TzOi5jP4wpLJfxBMQUpFTowYOMawlXkGam5mR7Jb+NVAqYueuT4FDvfTc4W1kAXak69mqulJ0xv+tAEuJuWIsWQgFaucAIbbYTN1MVrEaxEf3rWR2frBNknHHuu3oIQdexAyk5zrUtoajCGUKn5x8rEbuOKXC8eCR+eRxt0sjJ4rywN3CGRVeU41+jTLXsReSsOrug/yzkzFPQ+CHjRciUIna3admvFGEYNT7waMehnGOSIQ=
