language: r
sudo: false

cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_site"

env:
  global:
  - secure: WalkdPBoN2dH9a+aMqqbxRd1jHxVc77fcpF4PWfgMAU8P4ic4x36i+KZe8r12gQn5lzf8M6kBnwN1tY9dad6ZpGH3ofHMNA+hx9f59n1s5B/oZTaVjc2RdUz7gQxtAsOzZtdANWd/jtOCe8EbPYlONILMbvpFvgTUpVrLgvO0BtwR/EVghQT42StlNK6tj3HC+eAu32YFZ1M7bJ1yqBbovhCg7httKo+yhVnpAfzpRHutP4NMQbhm82ME6jX6N+oNinXOSryD8luopU/dEkhrIoZPDVP+RAUe4qZ2Nh+vrEJISJTFtb+wFmZQoL1RRwX4cj+svmQdrZHBaYo0MidJVTk49kdTv/V/SO6IyVe9gVrzFKSrJp77ISGNcz7YUcscn8L33crFx7TmSaauW3VxOdjWy7IGjJuSZLcBHaahBgkaKz3M+W/LAU24ezN2JZc8YLcpNJomtHOHAksASn/UohA8BTvf0VBz/L0t7b2E0LRtzkQoO3y3C4aeX3MIRTeXWCDYMLBzOJPBJaOYNRe1/M0pNf2V8M92nOE49xqkdx/pDY2SdCKCr5ojAt1clU3bhoUO7F6k5pVOsKdUae21n11aWTTn2Igs+GhJyeIbb/9wawwFYLdinkZi+V9N3csuzaMF0QuxQysl/a4yI3skp2SszbGf203Oc80j6HJoxI=
  - secure: cFXDf0maWjcFAv/ZyAshHwmylKvkgptUg34Qz3nvAfIKAf0vPLdHD5nT9troHp24gQXrQ+qsisrJx2rWtEQwCZrGcCb/Jc6h760dcZMW7RkH5ISFJpAqScrrZ96vvIcVGyxM07f0eaEmvtB7aRroSWlZ3AXijPvbKt0AcJjFjY6Gyic+jYDiHmMGoDlNDQNOOXBWlb4JeEsZG6XRJ+52djlBOR5/nstYjOdfwUI3j/3gS3YJsIQ/eya3QUa9cM7KwXDOFBmPfqpEJ2hwtsO1Us/ua4BhaskaH18wjPWNDNEWLeuokhCYeMq6xCFq/SgAU7ouCc9r5yYOsGM9EsC60Pg2xNfTVLvQN4mbpa/BeJXqojAn3x7Xb0YGGu1qf1tf2rgBMUQbdwmo35Cs/0xKHmBTtwMo8YAc8wkU+1GfsLmCDtL1hjnQ8KJzXSFyw56JXaYJx8o3mNywl7pWTXDbVpuanPPgx++AVE0vkiT3/3iiKPt4ltaFym6yS57/g8+/rVf32sZpyLwSPG3nDOK2CeGrhs64fzYmvYhpgZuGgKdl17jtVejcAzK/4OaZz0g2QXNCOesQZuCuuXYiRv1rUg6yIrgucG/FgpGGs40Z5qK8vKLpRfUztJZ1haGCrsxvmhQQgvU2sENxsOaLoxXjsH7noXY8co0oZbp0r46Yqy4=

script:
- make -f build.mk

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  local_dir: _site
  github_token: "$GITHUB_TOKEN"

notifications:
  email: false
  slack:
    secure: 2+MfOJY+S8mg161dILzZ3YQIVWLwcDg9OTRD0dWn8QwSUyYUSUCs6aFWzSAMnpHCIHDGPdb20Bl4zvxpKIBcvLuGl/1Q1Klcv7XKS6bNHwfK0TmJL90TVpJUAXPRC40HVfPcxRbk1RzIegx4gtwu13zv1rtButiel+BlSEfZAJp9hOgWFFT4T1Z3fX8b0vhUYDBwAmTXzSkJu4zNJywpWDBBqgZwZl4QVCy8epaxSfYXKl8ZlIZBmWnNhFEGd8xzTmSrHwVZL8/EVpVQaXSHgQk+WWYS0sHvjTg77vnZqTE55+Cy2jdXOcK5oN/I+CLpT32mGNaT52FWX/WwXSPj+lbp0LWAsyRBLDRBOLtTNPnldWHlst8MgglolKSgj8W5zCjxYITxwaE3EHG9+diOuJZRZHLit5dRNXGZ6F92evxBhAARbYvIUDK8Tydj+gb4TfCAcoYL9gSm1GAOqSgsGxQJUDf79takrIhQR32qHkz52srflvqjlo4fP0OYnobuBGo1m9RcCVqULq2N7Jz2utu0HsmgRTFx3liXfbxwW8c0510K6AwQn9gF1Iv7tAqN+iAqjtg+dBgLIRnHVAIPtSX7rVutnRPqnob8tjjs0b8qS1hzdaBfLJalhFdDiAodWRkdlH/QwUNgQDuslZebgs3pHPOyiQ4k9cRwPjTnXFg=
